### ISSUE TITLE
greengrass config.yaml missing information

### ISSUE THREAD

**Issue by n3o33** [aws/meta-aws#111]
Hey all, 
where can i find the following informations ? 

awsRegion: ##aws_region##
iotCredEndpoint: ##iot_cred_endpoint##
iotDataEndpoint: ##iot_data_endpoint##
iotRoleAlias: ##role_alias##

i want to fill that information without using the "auto setup" with the AKS Keys. Is there a way to simple get the info from console.aws.amazon.com

thx for helping me out

**Comment by rpcme** [comment]
Hi @n3o33

awsRegion: that is the region you would like Greengrass to talk to, i.e. Virginia is us-east-1.
iotCredEndpoint/iotDataEndpoint: I only know how to get these from the command line, i.e.
```bash
aws iot describe-endpoint --endpoint-type iot:Data-ATS
aws iot describe-endpoint --endpoint-type iot:CredentialProvider
```
iotRoleAlias: this is up to you, please see the instruction here:  https://docs.aws.amazon.com/greengrass/v2/developerguide/device-service-role.html
