### ISSUE TITLE
Add C++ only option

### ISSUE THREAD

**Issue by sks2021** [aws/meta-aws#121]
It would be good to have python (meta-python and dependent projects) under some conditional flags like DISTRO_FEATURES or something similar so that someone can build without python.

**Comment by rpcme** [comment]
hello @sks2021 I would like clarity on the meaning of this issue - do you mean we should not automatically include the python interpreter?  I think core already includes a barebones python interpreter for system function.  Maybe I'm missing it but I don't think the Device SDK for C++ forces you to install python? Thank you

**Comment by rpcme** [comment]
Closing this issue as a non-issue - C++ recipes do not depend on python
