### ISSUE TITLE
High CPU utilization of Device Client

### ISSUE THREAD

**Issue by dhwalters423** [aws/meta-aws#134]
There has been a critical fix in the Device Client that should be in the next minor release of Device Client (1.3). Please update to the newest Device Client as soon as its feasible. Details in this ticket: https://github.com/awslabs/aws-iot-device-client/issues/147

**Comment by rpcme** [comment]
@dhwalters423 I see this is fixed but the team hasn't yet made another release.  I will need to wait for a tagged, semantically versioned contiguous set is available before taking the fix.

**Comment by rpcme** [comment]
@dhwalters423 we are in plan to put in the latest device client but still facing aws-lc not being tagged.  Hopefully this will be resolved over the next 2 weeks.

**Comment by rpcme** [comment]
@dhwalters423 New version of Device Client (1.3.4) is staged on master-next and will likely be pushed to master in the morning.  all currently maintained release branches will fast follow.
