### ISSUE TITLE
Request to add support for aws-iot-securetunneling-localproxy project

### ISSUE THREAD

**Issue by kareali** [aws/meta-aws#140]
Recently, support for `aws-iot-securetunneling-localproxy` was removed from the Yocto project due to a problem with boost 1.69 (#126), this is a notification that we've updated the localproxy project to the latest boost stable version (1.76), so you should be able to add the recipes for the SecureTunneling support again.

**Comment by rpcme** [comment]
@kareali Thank you for the notification - will work on getting this added back today!

**Comment by rpcme** [comment]
@kareali is it possible you can do a tagged release so I can reference the tag instead of the commit hash?
