### ISSUE TITLE
Yocto recipe for Firecracker

### ISSUE THREAD

**Issue by rpcme** [aws/meta-aws#18]
Add recipe to build and install Firecracker.

Firecracker is an open source project supported by AWS.  From their landing page:

Firecracker is an open source virtualization technology that is purpose-built for creating and managing secure, multi-tenant container and function-based services that provide serverless operational models. Firecracker runs workloads in lightweight virtual machines, called microVMs, which combine the security and isolation properties provided by hardware virtualization technology with the speed and flexibility of containers.

Note: The Arm build is in preview.

https://github.com/firecracker-microvm/firecracker

**Comment by bbros-dev** [comment]
The [`meta-virtualization`](http://git.yoctoproject.org/cgit/cgit.cgi/meta-virtualization/) layer may be of interest to others coming along this path.

HTH

**Comment by jwinarske** [comment]
Firecracker Recipe: https://github.com/jwinarske/meta-microvm

Builds on NVIDIA Xavier NX BSP (aarch64)

**Comment by rpcme** [comment]
@jwinarske nice! is there a reason why you just didn't do a PR to this layer?

**Comment by jwinarske** [comment]
Keep in mind it brings in layer dependencies of meta-clang, and meta-rust.  I'm finding I like the approach of having them separate when target doesn't need rust.  Something like meta-aws-rs might be good.  But I can PR into here.

**Comment by rpcme** [comment]
We can loosely couple the dependencies through the layer config - like we have for greengrass when wanting docker, specific runtimes, or other heavyweight dependencies.

Super appreciate it :)

**Comment by jwinarske** [comment]
https://github.com/aws/meta-aws/pull/128

**Comment by rpcme** [comment]
Fixed by #128 thank you @jwinarske!
