### ISSUE TITLE
Why recipe for awscli is not in the dunfell branch ?

### ISSUE THREAD

**Issue by ARaffalli-STM** [aws/meta-aws#224]
Hi, 
I am trying to use the meta-aws project to test AWS on STM32MP157. Our Yocto release is Dunfell and I cannot find the awscli*.bb recipe when I checkout "remotes/origin/dunfell".
What is the reason for this ? Can I just add the recipe manually?
Thanks,
Anna

**Comment by ARaffalli-STM** [comment]
Hi Richard,
Thanks for your answer! Actually it may not block me since I figured it could be enough for me to use the awscli from my dev PC instead of the target (IoT Edge device).
Anna

**Comment by nateglims** [comment]
It's on  dunfell-next now.

**Comment by nateglims** [comment]
It has since been merged into dunfell.
