### ISSUE TITLE
Request to create honister branch as it was released a couple of weeks back

### ISSUE THREAD

**Issue by rarengifoArthrex** [aws/meta-aws#247]
Create honister branch and continue having master branch as well.

**Comment by nateglims** [comment]
Hi @rarengifoArthrex thanks for taking notice. We will be creating the new release branch shortly.

**Comment by rpcme** [comment]
@rarengifoArthrex This will happen 11/8/2021. Thank you for bringing this up.

**Comment by nateglims** [comment]
The `honister` branch and it's staging branch, `honister-next` have been created.
