### ISSUE TITLE
Support for AWS KVS in meta-aws

### ISSUE THREAD

**Issue by qraleq** [aws/meta-aws#262]
Hi, I'm interested in whether there's a timeline for AWS KVS support in meta-aws?

**Comment by aduskett** [comment]
Hello, while I can't directly answer that question, if you are willing to use buildroot I have a buildroot version of meta-aws that includes the kvs packages found here: https://github.com/aduskett/buildroot-aws-iot/

Might be worth a look! 

Adam

**Comment by nateglims** [comment]
Hi Ivan, We do not have a timeline for KVS support right now. If you're able to discuss what you are trying to do, we might be able to help you though.

**Comment by qraleq** [comment]
Hi, thank you both for your answers. 

We're trying to build AWS KVS and AWS IoT Greengrass on IP cameras running Yocto (for example AXIS CCTV cameras). 

@aduskett I'll take a look into `buildroot-aws-iot`, and it would be great if we could connect to see if you can help us to achieve our goal.

Thank you!

**Comment by rpcme** [comment]
@qraleq Thank you for asking about KVS support.  I'm reaching out to folks internally to see how we can bridge support for it sooner rather than later.

**Comment by qraleq** [comment]
Hi @rpcme, do you have any update on this?

**Comment by rpcme** [comment]
Hello @qraleq we are currently scoping this.  Please stay tuned. I would also love to hear the urgency.  If this is blocking you, this will lift the priority and we might be able to shift resources to accomodate.

**Comment by qraleq** [comment]
Hi @rpcme, 

At the moment we're using NVIDIA edge devices in combination with AXIS cameras to stream and analyze the CCTV streams. Unfortunately, with the global chip shortage, NVIDIA devices are impossible to get and we're considering moving the streaming service directly to the camera. That's where `meta-aws` might be really helpful to support KVS on the cameras themselves.

So, this is pretty high priority for us. Thank you!

**Comment by rpcme** [comment]
@qraleq I would like one more clarification/scope question:  You are asking for KVS SDK for Data Streams and you would also like Yocto SDK support for cross compile environment?  Want to ensure we have the requirements right so what is delivered meets / exceeds your expectations.

**Comment by qraleq** [comment]
Hi @rpcme, we're interested in AWS Kinesis Video Streams Producer SDK, and it would be great to have support for cross-compile using Yocto SDK.

**Comment by rpcme** [comment]
@qraleq perfectly understand and sorry for the data streams confusion, I have for another reason kinesis data streams on my mind :D

**Comment by rpcme** [comment]
Hello @qraleq I have started the recipe development. There are many things in the upstream cmake that's not "Yocto ready" so it will take some time to complete - perhaps another week but I'll try to bring it in.

Which language are you targeting? This is the status:

1/ PIC (completed, not yet in master-next)
2/ C (in progress, depends on PIC)
3/ C++ (in progress, depends on C)
4/ Java - I plan to do this last but if this is the language you're really targeting let me know.

**Comment by qraleq** [comment]
Hi @rpcme, we would be interested in C and C++. Thank you so much for your help.

**Comment by rpcme** [comment]
Hi @qraleq I completed C but have a hard stop in about 30 minutes.  You might be aware it is public holiday in US on Monday so I will likely not have anyone to do CR on Monday. In such case, you will have at least C by COB Tuesday.

**Comment by rpcme** [comment]
Hello @qraleq I have "completed" the initial work on the recipes and done a PR. In the meantime, you can try from my fork if you desire. 

https://github.com/rpcme/meta-aws/tree/master/recipes-sdk/amazon-kvs-producer-sdk

I have not yet runtime verified but will at least make sure over the next couple hours that all runtime dependencies are in place, I need to build an image for that, and then after build an example to ensure I get KVS running video to the cloud ok (I don't expect issues with that once deps are verified).

Also, another point is the CMake files are not shipping the SDK cmake files, so please let me know if you expect to lean on those in an SDK context. Customer do use them in our Device SDKs so I have that as a follow on task for the implementation.

**Comment by rpcme** [comment]
Ok it looks decen
![Screenshot from 2022-01-16 06-31-18](https://user-images.githubusercontent.com/2113279/149658107-3fff43d5-9b88-4d17-b0dc-8095d5aacf55.png)
t

**Comment by rpcme** [comment]
Hello @qraleq this work was put on master-next and should be put onto master branch today (PR is in progress). Closing this request.
