### ISSUE TITLE
Dunfell Corretto recipe contains incorrect ARM checksums.

### ISSUE THREAD

**Issue by greencustard** [aws/meta-aws#266]
While building Greengrass v2 I hit a problem with the arm.md5sum and arm.sha256sum for the following Corretto recipe:

meta-aws/recipes-devtools/amazon-corretto/corretto-11-bin_11.0.12.7.1.bb

This is the file being fetched:
https://corretto.aws/downloads/resources/11.0.12.7.1/amazon-corretto-11.0.12.7.1-linux-armv7.tar.gz;name=arm

These are the current (incorrect checksums) in the above recipe:

SRC_URI[arm.md5sum]        = "67cb4d9d4a313c4f001d81717f2b7cd4"
SRC_URI[arm.sha256sum]   = "4648ea4419ddc20bdb6f2378355d289cbaadd588b41e112c03d03d06eaa075e2"

These are the correct checksums for the Amazon Corretto tar ball: 

SRC_URI[arm.md5sum]        = "b7d9f46eabd604c0bf89227bc64644ed"
SRC_URI[arm.sha256sum]   = "63c05e86606d53df6a33472bb570fa9318de8125644dd928566d6205a1ecb024"

**Comment by hancin** [comment]
it appears the corrections were done in #250 in master branch. can that change be applied to other release branches?

**Comment by nateglims** [comment]
The checksum should be fixed on `dunfell-next` I am preparing a release into dunfell. It should be merged some time tomorrow.

**Comment by nateglims** [comment]
This should now be resolved on `dunfell`
