### ISSUE TITLE
Greengrassv2 for Thud version

### ISSUE THREAD

**Issue by Praveenaboyapally** [aws/meta-aws#276]
Hi,
There is no greengrass v2 for thud version, As yocto project supports only thud version we need to build a greengrass v2 in our embedded device. Please provide the required support for Greengrass version2 recipe in meta-aws thud version.

Thanks.

**Comment by rpcme** [comment]
Hello @Praveenaboyapally , we are currently in **breakfix** mode for Thud.  In such case, only recipes on that branch are maintained and no new recipes are targeted by us.  Also remember that GGv2 is Armv8 or Intel64.  If you have the hardware use case where it meets the condition, we will consider a community contribution for the recipe.

**Comment by rpcme** [comment]
Reolving.
