### ISSUE TITLE
AWS IoT Device SDK for Javascript V2

### ISSUE THREAD

**Issue by rpcme** [aws/meta-aws#36]
NOTE at the time of writing this is now in developer preview

Implement recipe for AWS IoT Device SDK for Javascript V2

https://github.com/aws/aws-iot-device-sdk-js-v2

**Comment by rpcme** [comment]
Moved tracking to internal

**Comment by gsalomao** [comment]
@rpcme Could you please update the current status of this recipe? If you have not started it, I can create the recipe and submit the PR.
