### ISSUE TITLE
dunfell branch

### ISSUE THREAD

**Issue by codrin989** [aws/meta-aws#56]
Hi @rpcme ,

Now with the yocto dunfell release, do you plan to create a new dunfell branch? I know it's an extra branch to maintain, but the master branch will be used with newer yocto packages and meta-aws might need new patches to support them, while dunfell will get only fixes.
Thanks!

**Comment by rpcme** [comment]
Hello @codrin989 Sorry for the delay, I have been on leave.

Yes will do, lovely that the release happened when I was on leave :) thanks for the heads up. When I get to my desk this morning, I will fork.

**Comment by codrin989** [comment]
There is no delay, I just opened the 'iissue' last day. Thanks! :)

**Comment by rpcme** [comment]
This branch has now been created.

**Comment by codrin989** [comment]
Thanks @rpcme !
