### ISSUE TITLE
greengrassSystemComponents needs ELF patch for x86_64

### ISSUE THREAD

**Issue by kriskep** [aws/meta-aws#60]
Binary file `ggc/core/lambda/GreengrassSystemComponents/greengrassSystemComponents`  needs patchelf to --set-interpreter to /lib/... instead of /lib64/... for x86_64 arch.

**Comment by rpcme** [comment]
Hi @kriskep, please check 1.10.1 that I just committed. there is an issue with the previous fix where it was specific to qemu.    Right now I have it only on master but can pull it down to zeus or whatever, depending on the immediate need.

**Comment by kriskep** [comment]
Hi @rpcme, there is second binary that needs patchelf. Please check my pull request #65

**Comment by rpcme** [comment]
Thank you! I think this should resolve extending issues on this topic. If there's more issues, please share.

**Comment by kriskep** [comment]
Hi @rpcme, unfortunately, there is yet another binary that needs this patch:
`/greengrass/ggc/packages/1.10.1/lambda/arn.aws.lambda...function.GGIPDetector.1`

It only shows up when you start to deploy things. 
**Maybe it is safer to create a symlink in /lib64. What do you think?** It would also save us from future changes in the binary package.
