### ISSUE TITLE
the bbappend file in the base directory is never picked up

### ISSUE THREAD

**Issue by kriskep** [aws/meta-aws#61]
ref. to this line:
https://github.com/aws/meta-aws/blob/cae4329eaaaf68704c8aa3ddfee8a3ce489118ba/recipes-greengrass/greengrass-core/greengrass.inc#L29

I believe this does not work to add bbappend files conditionally. `bitbake-layers show-appends` does not show it.

**Comment by rpcme** [comment]
This issue has been fixed.
