### ISSUE TITLE
Kinesis VIdeo Stream WebRTC SDK - C

### ISSUE THREAD

**Issue by rpcme** [aws/meta-aws#73]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c

**Comment by vijayrakesh13** [comment]
Can you please share Amazon Kinesis Video Stream recipe for the Yocto Metadata Layer for baking into Embedded Linux distributions.

**Comment by rpcme** [comment]
issue moving to track internal

**Comment by ajlennon** [comment]
Is this available anywhere?
